# Generated by Django 3.0.5 on 2023-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20231102_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='wikipedia_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
